### ISSUE TITLE
Where can I find the source for this site?

### ISSUE THREAD

**Issue by jikkujose** [grommet/grommet.github.io#1]
Is the source for this site open?

**Comment by alansouzati** [comment]
Yes, the project is [grommet-docs](https://github.com/grommet/grommet-docs).

For now, this new site is in a separate branch: https://github.com/grommet/grommet-docs/tree/new-site

Soon we will move this to the main branch.

**Comment by jikkujose** [comment]
Thanks! Great work pal, but frankly `npm install` takes forever :). Also wish this was in Webpack than gulp.

**Comment by alansouzati** [comment]
You are not required to use `grommet-toolbox` to use Grommet. If you look grommet-core dependencies it is rather small:

https://github.com/grommet/grommet/blob/master/package.json#L29

On the other hand, grommet-toolbox runs on top of Webpack and Gulp and requires much more dependencies than grommet core:

https://github.com/grommet/grommet-toolbox/blob/master/package.json#L19

If you want to use bare grommet without the development stack I would be surprised by `npm install` taking a long time.

**Comment by jikkujose** [comment]
Hmm, thats surprising that it doesn't take this long there; have you tried to `npm install` after deleting your dependencies? I just wanted to recompile the `sass` files with different colours for changing the theme. I couldn't get `npm install` to finish! It downloaded well over 400 MB!

Is it possible to use `webpack` to build grommet.
